/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia.pkg5;

import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author Diegp
 */
public class frmfigura4lados extends javax.swing.JFrame {

    /**
     * Creates new form frm4lados
     */
    public frmfigura4lados() {
        initComponents();
        this.getContentPane().setBackground(Color.green);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbase = new javax.swing.JTextField();
        txtaltura = new javax.swing.JTextField();
        btncalcular = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtarea = new javax.swing.JTextField();
        txtdiagonal = new javax.swing.JTextField();
        btncalculardiagonal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulos.setText("Calcular la diagonal y el area de una figura de 4 lados");
        getContentPane().add(lbltitulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, 71));

        jLabel2.setText("Ingrese la base");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 131, 21));

        jLabel3.setText("ingrese la altura");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 131, 19));
        getContentPane().add(txtbase, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 107, -1));

        txtaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalturaActionPerformed(evt);
            }
        });
        getContentPane().add(txtaltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 107, -1));

        btncalcular.setText("Calcular Area ");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel6.setText("El area es :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, 20));

        jLabel7.setText("La diagonal es:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));
        getContentPane().add(txtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 90, -1));

        txtdiagonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiagonalActionPerformed(evt);
            }
        });
        getContentPane().add(txtdiagonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 90, -1));

        btncalculardiagonal.setText("Calcular Diagonal");
        btncalculardiagonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculardiagonalActionPerformed(evt);
            }
        });
        getContentPane().add(btncalculardiagonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalturaActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
       
        double base=Double.parseDouble(txtbase.getText());
        
       double altura=Double.parseDouble(txtaltura.getText());
        txtarea.setText(String.valueOf(base*altura));   
        
    }//GEN-LAST:event_btncalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  GUIA1 jframe= new GUIA1 ();
        jframe.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtdiagonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiagonalActionPerformed
      
    }//GEN-LAST:event_txtdiagonalActionPerformed

    private void btncalculardiagonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculardiagonalActionPerformed

        txtdiagonal.setText(String.valueOf(sqrt(txtarea)));      
    }//GEN-LAST:event_btncalculardiagonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmfigura4lados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmfigura4lados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmfigura4lados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmfigura4lados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmfigura4lados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btncalculardiagonal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbltitulos;
    private javax.swing.JTextField txtaltura;
    private javax.swing.JTextField txtarea;
    private javax.swing.JTextField txtbase;
    private javax.swing.JTextField txtdiagonal;
    // End of variables declaration//GEN-END:variables

    private Object sqrt(JTextField txtarea) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
