/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia.pkg5;

/**
 *
 * @author Diegp
 */
public class Frmvolumencubo extends javax.swing.JFrame {

    /**
     * Creates new form Frmcubo
     */
    public Frmvolumencubo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblvolcubo = new javax.swing.JLabel();
        lbldiagonal = new javax.swing.JLabel();
        txtdiagonalcubo = new javax.swing.JTextField();
        lblresultadoarista = new javax.swing.JLabel();
        txtresultadoarista = new javax.swing.JTextField();
        btncalcularcubo = new javax.swing.JButton();
        lblarea = new javax.swing.JLabel();
        txtresultadocubo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblvolcubo.setText("Volumen de un Cubo");
        getContentPane().add(lblvolcubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 11, -1, -1));

        lbldiagonal.setText("Ingrese la Diagonal");
        getContentPane().add(lbldiagonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 47, -1, -1));

        txtdiagonalcubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiagonalcuboActionPerformed(evt);
            }
        });
        getContentPane().add(txtdiagonalcubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 44, 67, -1));

        lblresultadoarista.setText("Resultado de la arista es:");
        getContentPane().add(lblresultadoarista, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 87, -1, -1));
        getContentPane().add(txtresultadoarista, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 84, 156, -1));

        btncalcularcubo.setText("Calcular");
        btncalcularcubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularcuboActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcularcubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 43, -1, -1));

        lblarea.setText("Resultado de volumen es: ");
        getContentPane().add(lblarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 125, -1, -1));
        getContentPane().add(txtresultadocubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 122, 156, -1));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 191, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularcuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularcuboActionPerformed
        double diagonal=Double.parseDouble(txtdiagonalcubo.getText());
        txtresultadoarista.setText(String.valueOf(diagonal/1.414213562));
       double arista=Double.parseDouble(txtresultadoarista.getText());
        txtresultadocubo.setText(String.valueOf(arista*arista*arista));
    }//GEN-LAST:event_btncalcularcuboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  GUIA1 jframe= new GUIA1 ();
        jframe.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtdiagonalcuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiagonalcuboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiagonalcuboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmvolumencubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmvolumencubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmvolumencubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmvolumencubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmvolumencubo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcularcubo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblarea;
    private javax.swing.JLabel lbldiagonal;
    private javax.swing.JLabel lblresultadoarista;
    private javax.swing.JLabel lblvolcubo;
    private javax.swing.JTextField txtdiagonalcubo;
    private javax.swing.JTextField txtresultadoarista;
    private javax.swing.JTextField txtresultadocubo;
    // End of variables declaration//GEN-END:variables
}
