/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia.pkg5;

/**
 *
 * @author Diegp
 */
public class GUIA1 extends javax.swing.JFrame {

    /**
     * Creates new form APP1
     */
    public GUIA1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnarea4lados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnvolumencircunferencia = new javax.swing.JButton();
        btnvolumenesfera = new javax.swing.JButton();
        btnvolumencubo = new javax.swing.JButton();
        btnpromedio = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnarea4lados.setText("Calcular el Area Y Diagonal de un cuadrado");
        btnarea4lados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarea4ladosActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Que desea hacer?");

        btnvolumencircunferencia.setText("Calcular circuferencia de un circulo");
        btnvolumencircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolumencircunferenciaActionPerformed(evt);
            }
        });

        btnvolumenesfera.setText("Calcular Volumen de Una Esfera");
        btnvolumenesfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolumenesferaActionPerformed(evt);
            }
        });

        btnvolumencubo.setText("Calcular volumen de un cubo");
        btnvolumencubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolumencuboActionPerformed(evt);
            }
        });

        btnpromedio.setText("Calcular Promedio");
        btnpromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpromedioActionPerformed(evt);
            }
        });

        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnpromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnvolumencircunferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnarea4lados)
                            .addComponent(btnvolumenesfera, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnvolumencubo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnregresar)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnarea4lados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnvolumencircunferencia)
                .addGap(18, 18, 18)
                .addComponent(btnvolumenesfera)
                .addGap(18, 18, 18)
                .addComponent(btnvolumencubo)
                .addGap(18, 18, 18)
                .addComponent(btnpromedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnregresar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnarea4ladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarea4ladosActionPerformed
        frmfigura4lados jframe = new frmfigura4lados();
        jframe.setVisible(true);
    }//GEN-LAST:event_btnarea4ladosActionPerformed

    private void btnvolumencircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolumencircunferenciaActionPerformed
        frmcirculo jframe = new frmcirculo();
            jframe.setVisible(true);
    }//GEN-LAST:event_btnvolumencircunferenciaActionPerformed

    private void btnvolumenesferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolumenesferaActionPerformed
        frmesfera jframe= new frmesfera();
        jframe.setVisible(true);
    }//GEN-LAST:event_btnvolumenesferaActionPerformed

    private void btnvolumencuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolumencuboActionPerformed
        Frmvolumencubo jframe= new Frmvolumencubo ();
        jframe.setVisible(true);
    }//GEN-LAST:event_btnvolumencuboActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        FrmMenu jframe= new FrmMenu ();
        jframe.setVisible(true);
    }//GEN-LAST:event_btnregresarActionPerformed

    private void btnpromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpromedioActionPerformed
        frmpromedio jframe= new frmpromedio ();
        jframe.setVisible(true);
    }//GEN-LAST:event_btnpromedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIA1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIA1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIA1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIA1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIA1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnarea4lados;
    private javax.swing.JButton btnpromedio;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnvolumencircunferencia;
    private javax.swing.JButton btnvolumencubo;
    private javax.swing.JButton btnvolumenesfera;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
