package guia.pkg5;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Event;
import javax.swing.JOptionPane;



public class GUIA3Y4 extends javax.swing.JFrame {
    
    int valor9, valor=0;
    double valor2=0, valor4=0, valor7=0;
    String valor1="", valor3="", valor5="", valor6="", valor8="";

    
    public GUIA3Y4() {
        initComponents();
        this.getContentPane().setBackground(Color.orange);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdato = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdato2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblcamaras = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        txtcamara = new javax.swing.JTextField();
        btnejecutar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEjecutar = new javax.swing.JTextArea();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Puntajes de Moviles");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 35, 110, -1));

        jLabel2.setText("CPU numero de Nucleos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 78, 143, -1));

        txtdato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatoActionPerformed(evt);
            }
        });
        txtdato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdatoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdatoKeyTyped(evt);
            }
        });
        getContentPane().add(txtdato, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 75, 205, -1));

        jLabel3.setText("Tamaño de Pantalla");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 116, 115, -1));

        txtdato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdato2ActionPerformed(evt);
            }
        });
        txtdato2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdato2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdato2KeyTyped(evt);
            }
        });
        getContentPane().add(txtdato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 113, 205, -1));

        jLabel4.setText("RAM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 159, 115, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 156, 205, -1));

        jLabel5.setText("Garantia ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 206, 115, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 203, 205, -1));

        jLabel6.setText("Precio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 259, 98, -1));

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 256, 205, -1));

        jLabel7.setText("Marca");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 304, 87, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEXUS", "PIXI", "LENOVO", "SONY", "APPLE", "SAMSUNG", "ALCATEL", "LG", "OTRA", " ", " " }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 301, 117, -1));

        lblcamaras.setText("Camaras");
        getContentPane().add(lblcamaras, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 357, 79, -1));

        jCheckBox1.setText("Principal");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 353, -1, -1));

        jCheckBox2.setText("Secundaria");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 353, -1, -1));

        jCheckBox3.setText("Flash");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 353, -1, -1));

        txtcamara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcamaraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcamaraKeyTyped(evt);
            }
        });
        getContentPane().add(txtcamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 404, 42, -1));

        btnejecutar.setText("Ejecutar");
        btnejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejecutarActionPerformed(evt);
            }
        });
        btnejecutar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnejecutarKeyPressed(evt);
            }
        });
        getContentPane().add(btnejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 435, -1, -1));

        txtEjecutar.setEditable(false);
        txtEjecutar.setColumns(20);
        txtEjecutar.setRows(5);
        jScrollPane1.setViewportView(txtEjecutar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 471, 514, 139));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatoActionPerformed
          
    }//GEN-LAST:event_txtdatoActionPerformed

    private void txtdatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatoKeyTyped
      
     char c= evt.getKeyChar();
        
        valor5=valor5+c;
        valor=Integer.parseInt(valor5);
        if(valor>12){
        JOptionPane.showMessageDialog(null, "No se aceptan numeros mayor a 12 ");
        txtdato.setText(null);
        evt.consume();
        valor=0;
        valor5="";
    }
    
        if(c<'0' || c>'9'){
            evt.consume();
    
}
            int num=2;
        if(txtdato.getText().length()>=num){
            evt.consume();
            
        }
                      
    }//GEN-LAST:event_txtdatoKeyTyped

    private void txtdato2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdato2KeyTyped
        char c=evt.getKeyChar();
        
        valor1=valor1+c;
        valor2=Double.parseDouble(valor1);
        
        if(valor2<3.0 || valor2>6.7){
            JOptionPane.showMessageDialog(null, "No se aceptan numeros mayores a 6.7 ni menores a 3.0");
            txtdato2.setText(null);
            evt.consume();
            valor2=0;
            valor1="";
        }
        if((c<'0' || c>'9') && c!='.'){
            evt.consume();
        }
        int num=3;
        if(txtdato2.getText().length()==num){
            evt.consume();
        }
       
    }//GEN-LAST:event_txtdato2KeyTyped

    private void txtdatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatoKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            txtdato2.requestFocus();
        }
    }//GEN-LAST:event_txtdatoKeyPressed

    private void txtdato2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdato2KeyPressed
                if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            jTextField3.requestFocus();
        }
    }//GEN-LAST:event_txtdato2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add 
        
          if(evt.getKeyCode()== KeyEvent.VK_ENTER){
          
              jTextField4.requestFocus();
          }        
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            jTextField5.requestFocus();
          }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            jComboBox1.requestFocus();
   
          }
        
    }//GEN-LAST:event_jTextField5KeyPressed

    private void txtdato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdato2ActionPerformed
     
    }//GEN-LAST:event_txtdato2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
          
     
     
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char c=evt.getKeyChar();
  
            
            valor6=valor6+c;
            valor9=Integer.parseInt(valor6);
            if(valor9>24){
                JOptionPane.showMessageDialog(null, "No se aceptan numeros mayores a 24");
                jTextField4.setText(null);
                evt.consume();
                valor9=0;
                valor6="";
            }
            
            if(c<'0' || c>'9') {
        evt.consume();
    }
            int num=2;
            if(jTextField4.getText().length()==num){
                evt.consume();
            }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
      char c=evt.getKeyChar();
            
            valor8=valor8+c;
            valor7=Double.parseDouble(valor8);
            if(valor7<0.01 || valor7>999.99){
                JOptionPane.showMessageDialog(null, "No se aceptan numeros menos a 0.01 ni mayores a 999.99");
                jTextField5.setText(null);
                evt.consume();
                valor7=0;
                valor8="";
            }
            if((c<'0' || c>'9') && c!='.'){
        evt.consume();
    }
            int num=6;
            if(jTextField5.getText().length()==num){
                evt.consume();
            }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
            char c=evt.getKeyChar();
            
            valor3=valor3+c;
            valor4=Double.parseDouble(valor3);
            if(valor4<0.5 || valor4>6.0){
                JOptionPane.showMessageDialog(null, "No se aceptan numeros menos a 0.5 ni mayores a 6.0");
                jTextField3.setText(null);
                evt.consume();
                valor4=0;
                valor3="";
            }
            if((c<'0' || c>'9') && c!='.'){
        evt.consume();
    }
            int num=3;
            if(jTextField3.getText().length()==num){
                evt.consume();
            }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void txtcamaraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcamaraKeyTyped
        int num=4;
        
            if(txtcamara.getText().length()>=num){
                evt.consume();
            }
            
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
           
            
        }
        if(evt.getKeyChar()=='.' && txtcamara.getText().contains(".")){
            evt.consume();      
    }        
    }//GEN-LAST:event_txtcamaraKeyTyped

    private void txtcamaraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcamaraKeyPressed
     
    }//GEN-LAST:event_txtcamaraKeyPressed

    private void btnejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejecutarActionPerformed
       String cadena= " ",variable=" ";
       if(jCheckBox1.isSelected()){
           cadena= cadena + " Principal ";
          }
       if(jCheckBox2.isSelected()){
           cadena= cadena + " Secundaria ";
      
       }   if(jCheckBox3.isSelected()){
           variable= variable + " Y Flash ";
       }
        
    
       
       
       
           txtEjecutar.setText("El Numero del CPU es:"+valor+"\n"+"El Tamaño de la Pantalla es:"+valor2+"\n"+"La Memoria RAM es:"+valor4+"\n"+"La Garantia es de:"+valor6+ " Meses\n"+"Su precio es de: $"+jTextField5.getText()+"\n"+"Y la Marca es:"+jComboBox1.getSelectedItem()+"\n"+ "Posee Camara"+cadena+ "de:" +txtcamara.getText()+ "Mpx" + variable);
    
    }//GEN-LAST:event_btnejecutarActionPerformed

    private void btnejecutarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnejecutarKeyPressed
         
    }//GEN-LAST:event_btnejecutarKeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
   
            if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            txtcamara.requestFocus();
    }//GEN-LAST:event_jComboBox1KeyPressed
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIA3Y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIA3Y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIA3Y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIA3Y4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIA3Y4().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnejecutar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblcamaras;
    private javax.swing.JTextArea txtEjecutar;
    private javax.swing.JTextField txtcamara;
    private javax.swing.JTextField txtdato;
    private javax.swing.JTextField txtdato2;
    // End of variables declaration//GEN-END:variables
}
